[project]
name = "planetary-datasets"
version = "0.0.1"
description = "Datasets for ML models for planetary use-cases (e.g. solar mapping, land use, forecasting)"
authors = ["Jacob Bieker <jacob@bieker.tech>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
python = ">=3.13.9,<3.14"
fsspec = ">=2025.10.0,<2026"
pandas = ">=2.3.3,<3"
requests = ">=2.32.5,<3"
aiohttp = ">=3.13.2,<4"
pystac-client = ">=0.9.0,<0.10"
dask = ">=2025.11.0,<2026"
geojson = ">=3.2.0,<4"
shapely = ">=2.1.2,<3"
geopandas = ">=1.1.1,<2"
pyproj = ">=3.7.2,<4"
rasterio = ">=1.4.3,<2"
xarray = ">=2025.10.1,<2026"
s3fs = ">=2025.10.0,<2026"
gcsfs = ">=2025.10.0,<2026"
adlfs = ">=2025.8.0,<2026"
zarr = ">=3.1.3,<4"
datasets = ">=4.4.1,<5"
cfgrib = ">=0.9.15.1,<0.10"
h5py = ">=3.15.1,<4"
pybufrkit = ">=0.2.25,<0.3"
h5netcdf = ">=1.7.3,<2"
dagster = ">=1.12.2,<2"
dagster-webserver = ">=1.12.2,<2"
dagster-pipes = ">=1.12.2,<2"
dagster-docker = ">=1!0.28.2,<1!0.29"
icechunk = ">=1.1.12,<2"
cdsapi = ">=0.7.7,<0.8"
sqlite = ">=3.51.0,<4"
netcdf4 = ">=1.7.3,<2"
eumdac = ">=3.0.0,<4"
pip = ">=25.3,<26"
kerchunk = ">=0.2.9,<0.3"
fastparquet = ">=2024.11.0,<2025"
pvlib = ">=0.13.1,<0.14"
iris = ">=3.13.1,<4"
rioxarray = ">=0.20.0,<0.21"
satpy = ">=0.59.0,<0.60"
ruff = ">=0.14.5,<0.15"
harp = ">=1.28.1,<2"
eccodes = ">=2.44.0,<3"

[pypi-dependencies]
odc-stac = ">=0.4.0, <0.5"
planetary-computer = ">=1.0.0, <2"
pystac-client = "*"
lxml = ">=6.0.2, <7"
meteostat = ">=1.7.6, <2"
structlog = "*"
huggingface-hub = "*"
psutil = "*"
wetterdienst = ">=0.114.3, <0.115"
isd = ">=0.1.0, <0.2"
ocf-blosc2 = ">=0.0.14, <0.0.15"
nest-asyncio = ">=1.6.0, <2"
igra = ">=23.5, <24"
virtualizarr = { git = "https://github.com/zarr-developers/VirtualiZarr.git", extras = ["all_parsers"] }
